/**
 * CarPartStore-API
 * API des CarPartStore-Backends
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ata@hbt.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FcCarMarke = 'ALPHA_ROMEO' | 'AUDI' | 'BENTLEY' | 'BMW' | 'BUGATTI' | 'CHEVROLET' | 'CHRYSLER' | 'CITROEN' | 'DACIA' | 'DAEWOO' | 'DAIHATSU' | 'DODGE' | 'FERRARI' | 'FIAT' | 'FORD' | 'HONDA' | 'HYUNDAI' | 'JAGUAR' | 'JEEP' | 'KIA' | 'LADA' | 'LAMBORGHINI' | 'LAND_ROVER' | 'LEXUS' | 'MASERATI' | 'MAZDA' | 'MERCEDES_BENZ' | 'MINI' | 'MITSUBISHI' | 'MORGAN' | 'NISSAN' | 'OPEL' | 'PEUGEOT' | 'PORSCHE' | 'RENAULT' | 'ROLLS_ROYCE' | 'SEAT' | 'SKODA' | 'SUBARU' | 'SUZUKI' | 'TESLA' | 'TOYOTA' | 'VOLKSWAGEN' | 'VOLVO' | 'SONSTIGES';

export const FcCarMarke = {
    AlphaRomeo: 'ALPHA_ROMEO' as FcCarMarke,
    Audi: 'AUDI' as FcCarMarke,
    Bentley: 'BENTLEY' as FcCarMarke,
    Bmw: 'BMW' as FcCarMarke,
    Bugatti: 'BUGATTI' as FcCarMarke,
    Chevrolet: 'CHEVROLET' as FcCarMarke,
    Chrysler: 'CHRYSLER' as FcCarMarke,
    Citroen: 'CITROEN' as FcCarMarke,
    Dacia: 'DACIA' as FcCarMarke,
    Daewoo: 'DAEWOO' as FcCarMarke,
    Daihatsu: 'DAIHATSU' as FcCarMarke,
    Dodge: 'DODGE' as FcCarMarke,
    Ferrari: 'FERRARI' as FcCarMarke,
    Fiat: 'FIAT' as FcCarMarke,
    Ford: 'FORD' as FcCarMarke,
    Honda: 'HONDA' as FcCarMarke,
    Hyundai: 'HYUNDAI' as FcCarMarke,
    Jaguar: 'JAGUAR' as FcCarMarke,
    Jeep: 'JEEP' as FcCarMarke,
    Kia: 'KIA' as FcCarMarke,
    Lada: 'LADA' as FcCarMarke,
    Lamborghini: 'LAMBORGHINI' as FcCarMarke,
    LandRover: 'LAND_ROVER' as FcCarMarke,
    Lexus: 'LEXUS' as FcCarMarke,
    Maserati: 'MASERATI' as FcCarMarke,
    Mazda: 'MAZDA' as FcCarMarke,
    MercedesBenz: 'MERCEDES_BENZ' as FcCarMarke,
    Mini: 'MINI' as FcCarMarke,
    Mitsubishi: 'MITSUBISHI' as FcCarMarke,
    Morgan: 'MORGAN' as FcCarMarke,
    Nissan: 'NISSAN' as FcCarMarke,
    Opel: 'OPEL' as FcCarMarke,
    Peugeot: 'PEUGEOT' as FcCarMarke,
    Porsche: 'PORSCHE' as FcCarMarke,
    Renault: 'RENAULT' as FcCarMarke,
    RollsRoyce: 'ROLLS_ROYCE' as FcCarMarke,
    Seat: 'SEAT' as FcCarMarke,
    Skoda: 'SKODA' as FcCarMarke,
    Subaru: 'SUBARU' as FcCarMarke,
    Suzuki: 'SUZUKI' as FcCarMarke,
    Tesla: 'TESLA' as FcCarMarke,
    Toyota: 'TOYOTA' as FcCarMarke,
    Volkswagen: 'VOLKSWAGEN' as FcCarMarke,
    Volvo: 'VOLVO' as FcCarMarke,
    Sonstiges: 'SONSTIGES' as FcCarMarke
};

